//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenIntermex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Revista
    {
        [Display(Name = "#")]
        public int id_revista { get; set; }

        [Display(Name = "Titulo")]
        public string Titulo { get; set; }

        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; }

        [Display(Name = "Edicion")]
        public Nullable<int> Edicion { get; set; }

        [Display(Name = "Codigo de Barras")]
        public string CodigoBarras { get; set; }

        [Display(Name = "Precio")]
        public Nullable<decimal> Precio { get; set; }

        [Display(Name = "Fecha de Lanzamiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<int> Categoria_Id { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
